name       : python-pytest-cov
version    : 2.11.1
release    : 6
source     :
    - https://pypi.io/packages/source/p/pytest-cov/pytest-cov-2.11.1.tar.gz : 359952d9d39b9f822d9d29324483e7ba04a3a17dd7d05aa6beb7ea01e359e5f7
license    : MIT
component  : programming.python
summary    : Coverage plugin for pytest
description: |
    Py.test plugin for coverage reporting with support for both centralised and
    distributed testing, including subprocesses and multiprocessing for Python.
builddeps  :
    - python-setuptools
rundeps    :
    - python-coverage
    - python-pytest
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
